name: loglytics
description: An efficient, user-friendly way to implement logs, analytics and crash reports into your projects.
version: 0.9.2+1
homepage: https://github.com/codaveto/loglytics

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
