name: loglytics
description: A user friendly way of structuring debug logging, analytics and crash reports in your projects.
version: 0.1.3
homepage: https://github.com/codaveto/loglytics

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
